# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


configfile: "config/config.yaml"


pepfile: config["pepfile"]


include: "rules/common.smk"
include: "rules/contamination.smk"
include: "rules/qc.smk"
include: "rules/species_diversity.smk"
include: "rules/report.smk"


rule all:
    input:
        expand(
            "results/{date}/report/{date}_report.zip",
            date=get_run_date(),
        ),
        