pepfile: config/pep/config.yaml

run-date: "23_12_18"

adapter-seqs: "-a GCGAATTTCGACGATCGTTGCATTAACTCGCGAA -g AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"

data-handling:
  # path to store data within the workflow
  data: "data/"
  resources: "resources/"

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 15
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

human-ref: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.29_GRCh38.p14/GCA_000001405.29_GRCh38.p14_genomic.fna.gz"

kraken:
  download-path: "https://genome-idx.s3.amazonaws.com/kraken/k2_standard_20231009.tar.gz"
  db-name: "k2_standard"
